"use client";

import React from 'react';
import { AnimatedContainer } from '@/components/ui/AnimatedContainer';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { HelpCircle } from 'lucide-react';

const FAQS = [
  {
    value: "faq-1",
    qUrdu: "کیا حق دار اے آئی کے ذریعے تیار کردہ شکایات قانونی طور پر درست ہیں؟",
    qEnglish: "Are petitions generated by HaqDar AI legally valid?",
    aUrdu: "جی ہاں، تیار کردہ خطوط اور پٹیشنز پاکستان کے بنیادی قانونی فارمیٹ اور دائرہ اختیار کو مدنظر رکھ کر بنائی جاتی ہیں۔ تاہم، یہ مشورہ دیا جاتا ہے کہ کسی بھی بڑے قانونی اقدام سے پہلے لائسنس یافتہ وکیل سے رجوع کریں۔",
    aEnglish: "Yes, the generated documents are tailored using formal Pakistani administrative petition structures. However, they serve as templates; we recommend consulting a certified lawyer for critical legal procedures."
  },
  {
    value: "faq-2",
    qUrdu: "کیا میں شکایت صرف اردو زبان میں درج کروا سکتا ہوں؟",
    qEnglish: "Can I file complaints purely in Urdu speech?",
    aUrdu: "جی ہاں! ہمارا صوتی انجن اردو آواز کو مکمل طور پر سمجھتا ہے۔ آپ اردو میں بولیں گے، تو سسٹم نہ صرف اسے متن میں تبدیل کرے گا بلکہ اردو رسم الخط (Nastaliq) میں ہی بہترین پٹیشن تیار کرے گا۔",
    aEnglish: "Absolutely! HaqDar AI is specifically optimized for voice input in standard spoken Urdu. It automatically transcribes and formats the letter using Urdu script layout."
  },
  {
    value: "faq-3",
    qUrdu: "کیا میری شکایت براہِ راست متعلقہ ادارے کو جمع ہو جائے گی؟",
    qEnglish: "Does my complaint get submitted directly to the department?",
    aUrdu: "فی الحال یہ ایپ شکایت کا تفصیلی مسودہ (Draft) اور متعلقہ محکمے کی معلومات فراہم کرتی ہے۔ آپ کو تیار شدہ پٹیشن کاپی کر کے بذریعہ ڈاک، ای میل یا پورٹل متعلقہ محکمے کو خود بھیجنا ہوگی۔",
    aEnglish: "Currently, HaqDar AI analyses the case and drafts the petition for you. You will copy the prepared draft and send it to the designated department via physical mail, email, or official online portals."
  },
  {
    value: "faq-4",
    qUrdu: "کیا اس سروس کے استعمال کے کوئی اخراجات ہیں؟",
    qEnglish: "Are there any charges for using this service?",
    aUrdu: "نہیں، حق دار اے آئی مکمل طور پر مفت اور عوامی فلاح کے لیے بنایا گیا ہے تاکہ نچلے طبقے کے لوگوں کو اپنے حقوق کی آگاہی اور حصول آسان ہو سکے۔",
    aEnglish: "No, HaqDar AI is completely free to use. It is created as a civic empowerment tool to remove financial barriers to basic legal drafting."
  }
];

export function FaqSection() {
  return (
    <section className="w-full py-16 bg-[#3A231A]/5 border-t border-accent/10 relative overflow-hidden">
      <div className="container mx-auto px-4 max-w-4xl relative z-10">
        
        {/* Section Header */}
        <div className="text-center max-w-2xl mx-auto mb-12">
          <AnimatedContainer variant="fadeUp">
            <span className="text-[10px] font-bold uppercase tracking-[0.25em] text-accent font-inter block mb-2">
              Common Questions & Help
            </span>
            <h2 className="font-garamond text-3xl md:text-5xl font-black mb-3 gold-gradient-text-light">
              سوالات و جوابات / FAQ
            </h2>
            <div className="w-24 h-1 bg-accent/30 mx-auto rounded-full mt-4" />
          </AnimatedContainer>
        </div>

        {/* FAQs Accordion Container */}
        <AnimatedContainer variant="fadeUp" delay={0.2}>
          <div className="wood-console rounded-2xl p-4 md:p-6 border border-accent/20 shadow-2xl">
            <Accordion type="single" collapsible="true" className="space-y-4">
              {FAQS.map((faq) => (
                <AccordionItem 
                  key={faq.value} 
                  value={faq.value}
                  className="border-none"
                >
                  <AccordionTrigger className="w-full text-start py-4 px-5 rounded-xl bg-[#3A231A]/30 hover:bg-[#3A231A]/50 border border-[#523225] flex items-center justify-between cursor-pointer group transition-all duration-200">
                    <div className="flex items-start gap-3 flex-grow">
                      <HelpCircle className="w-5 h-5 text-accent shrink-0 mt-1.5 md:mt-1 group-hover:scale-110 transition-transform" />
                      <div className="space-y-1.5 w-full">
                        {/* Urdu Q */}
                        <h3 className="font-urdu text-xl md:text-2xl font-bold text-[#E6DBC6] leading-snug">
                          {faq.qUrdu}
                        </h3>
                        {/* English Q */}
                        <p className="font-inter text-xs text-accent/80 group-hover:text-accent font-semibold tracking-wide">
                          {faq.qEnglish}
                        </p>
                      </div>
                    </div>
                  </AccordionTrigger>
                  <AccordionContent className="pt-2 px-1">
                    <div className="parchment-sheet rounded-xl p-5 md:p-6 border border-accent/20 shadow-inner space-y-4">
                      
                      {/* Urdu A */}
                      <p className="font-urdu text-[16px] md:text-lg leading-[2.2] text-amber-950 dark:text-amber-100 font-medium">
                        {faq.aUrdu}
                      </p>
                      
                      <div className="w-full h-[1px] bg-accent/20" />

                      {/* English A */}
                      <p className="font-inter text-xs md:text-sm leading-relaxed text-amber-900/75 dark:text-amber-100/60">
                        {faq.aEnglish}
                      </p>

                    </div>
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </div>
        </AnimatedContainer>

      </div>
    </section>
  );
}
